const Router = require('express')
const router = new Router()
const user = require('./userRouter')
const component = require('./componentRouter')
const interface = require('./interfaceRouter')
const mail = require('./mailRouter')
const blocks = require('./blocksRouter')
const site = require('./siteRouter')
router.use('/user',user)
router.use('/component',component)
router.use('/interface',interface)
router.use('/mail',mail)
router.use('/blocks',blocks)
router.use('/site',site)
module.exports = router